{
 "title": "Pi System Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Network upload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(sysinfo_network_out_bytes[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Download",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(sysinfo_network_in_bytes[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "downsampler": "mean", "expression": "$system + $User + $Irq", "type": "math", "upsampler": "fillna" }
   ]
  },
  {
   "title": "Processor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sysinfo_sensor_temperature_celsius",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Ram Usage",
   "type": "timeseries",
   "description": "Ram usage as total -  free - cached - buffered - shared",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expression": "$Total - $Free - $Buffered - $Cached - $Shared",
     "type": "math"
    }
   ]
  },
  {
   "title": "Buffered Memory",
   "type": "timeseries",
   "description": "This is a relatively temporary storage for raw disk blocks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sysinfo_memory_buffers_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cached Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sysinfo_memory_cached_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Running Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sysinfo_processes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shared Memory",
   "type": "timeseries",
   "description": "Amount of shared memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sysinfo_memory_shared_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}